# Generated by Django 3.2.9 on 2021-11-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
    ]
