# Generated by Django 3.2.9 on 2021-11-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211113_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user_name',
            new_name='username',
        ),
    ]
